// Package knowledge generates .ctx-saver/project-knowledge.md from stored data.
package knowledge

import (
	"fmt"
	"strings"
	"time"

	"github.com/ChonlakanSutthimatmongkhol/ctx-saver/internal/store"
	"github.com/ChonlakanSutthimatmongkhol/ctx-saver/internal/version"
)

// knowledgeVersion is derived from the canonical version — update internal/version/version.go.
var knowledgeVersion = version.Version

// nowFn returns the current time; overridden in tests for deterministic output.
var nowFn = time.Now

// Render converts KnowledgeData to a project-knowledge.md markdown string.
func Render(data *store.KnowledgeData) string {
	var sb strings.Builder
	ts := nowFn()

	fmt.Fprintf(&sb, "# Project Knowledge\n")
	fmt.Fprintf(&sb, "> Auto-generated by ctx-saver v%s\n", knowledgeVersion)
	fmt.Fprintf(&sb, "> Last updated: %s | Based on: %d sessions | %d outputs | %d decisions\n",
		ts.Format("2006-01-02 15:04"),
		data.SessionCount,
		data.OutputCount,
		data.DecisionCount,
	)
	fmt.Fprintf(&sb, "> Run `ctx-saver knowledge refresh` to update manually\n")

	// Most-read files
	fmt.Fprintf(&sb, "\n## Most-read files\n")
	if len(data.TopFiles) == 0 {
		fmt.Fprintf(&sb, "_No file reads recorded yet._\n")
	} else {
		fmt.Fprintf(&sb, "| File | Reads | Cache stability |\n")
		fmt.Fprintf(&sb, "|------|-------|-----------------|\n")
		for _, f := range data.TopFiles {
			stability := "changing"
			if f.HashStable {
				days := int(ts.Sub(f.LastChanged).Hours() / 24)
				stability = fmt.Sprintf("stable (unchanged %dd)", days)
			}
			fmt.Fprintf(&sb, "| %s | %d | %s |\n", f.Path, f.ReadCount, stability)
		}
	}

	// Most-run commands
	fmt.Fprintf(&sb, "\n## Most-run commands\n")
	if len(data.TopCommands) == 0 {
		fmt.Fprintf(&sb, "_No commands recorded yet._\n")
	} else {
		fmt.Fprintf(&sb, "| Command | Runs | Avg output size |\n")
		fmt.Fprintf(&sb, "|---------|------|-----------------|\n")
		for _, c := range data.TopCommands {
			fmt.Fprintf(&sb, "| %s | %d | %s |\n", c.Command, c.RunCount, formatBytes(c.AvgBytes))
		}
	}

	// Common sequences
	fmt.Fprintf(&sb, "\n## Common sequences\n")
	if len(data.Sequences) == 0 {
		fmt.Fprintf(&sb, "_Not enough data to detect patterns yet._\n")
	} else {
		for _, s := range data.Sequences {
			fmt.Fprintf(&sb, "- `%s` → `%s` (%.0f%% co-occurrence)\n", s.First, s.Second, s.Percent)
		}
	}

	// Recent git commits
	fmt.Fprintf(&sb, "\n## Recent commits\n")
	if len(data.RecentCommits) == 0 {
		fmt.Fprintf(&sb, "_No git history available._\n")
	} else {
		for _, c := range data.RecentCommits {
			fmt.Fprintf(&sb, "- %s\n", c)
		}
	}

	// High-importance decisions
	fmt.Fprintf(&sb, "\n## High-importance decisions\n")
	if len(data.KeyDecisions) == 0 {
		fmt.Fprintf(&sb, "_No high-importance decisions recorded yet._\n")
	} else {
		order := make([]string, 0)
		byTask := make(map[string][]store.DecisionOut)
		for _, d := range data.KeyDecisions {
			task := d.Task
			if task == "" {
				task = "General"
			}
			if _, ok := byTask[task]; !ok {
				order = append(order, task)
			}
			byTask[task] = append(byTask[task], d)
		}
		for _, task := range order {
			fmt.Fprintf(&sb, "### %s\n", task)
			for _, d := range byTask[task] {
				prefix := ""
				if len(d.Tags) > 0 {
					prefix = "[" + strings.Join(d.Tags, ",") + "] "
				}
				fmt.Fprintf(&sb, "- %s%s\n", prefix, d.Text)
			}
		}
	}

	// Session patterns
	fmt.Fprintf(&sb, "\n## Session patterns\n")
	avgOutputs := 0
	if data.SessionCount > 0 {
		avgOutputs = data.OutputCount / data.SessionCount
	}
	fmt.Fprintf(&sb, "- Total sessions: %d | Total outputs: %d | Avg outputs/session: %d\n",
		data.SessionCount, data.OutputCount, avgOutputs)

	return sb.String()
}

func formatBytes(b int64) string {
	switch {
	case b < 1024:
		return fmt.Sprintf("%d B", b)
	case b < 1024*1024:
		return fmt.Sprintf("%.1f KB", float64(b)/1024)
	default:
		return fmt.Sprintf("%.1f MB", float64(b)/(1024*1024))
	}
}
